version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastbook_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  my-redis:
    image: redis
    container_name: my-redis-container
    ports:
      - 6380:6379
    restart: always
    volumes:
      - redis_volume_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_volume_data:

networks:
  app-network:
    driver: bridge